### ISSUE TITLE
Cannot install new plugin

### ISSUE THREAD

**Issue by tristanle22** [inventree/InvenTree#9701]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

I developed a plugin and uploaded it to Pypi. Trying to install the plugin through PUI, but always run into `ERROR: You must give at least one requirement to install (see "pip help install")`

Here's the trace:
```
Traceback (most recent call last):
File "/opt/inventree/src/backend/InvenTree/plugin/installer.py", line 266, in install_plugin
result = pip_command(*install_name)
File "/opt/inventree/src/backend/InvenTree/plugin/installer.py", line 37, in pip_command
return subprocess.check_output(
File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/inventree/env/bin/python3.9', '-m', 'pip', 'install', '-U', '--disable-pip-version-check', '-i', 'https://pypi.org/project']' returned non-zero exit status 1.
```

Seems like the argument list is missing the package name after 'install'.

### Steps to Reproduce

1. Go to "Install Plugin"
2. Enter `extracurrencyexchange` for Package Name
3. Enter `https://pypi.org/project/` for Source URL
4. Toggle ON for Confirm plugin installation

### Expected behaviour

Should install the plugin sucessfully

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

Version 0.17.9

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by SergeoLacruz** [comment]
Leave the  Source URL empty. Pypi if found automatically. 

![Image](https://github.com/user-attachments/assets/b942c301-02a6-4432-a972-5b41e9ac220e)

**Comment by tristanle22** [comment]
@SergeoLacruz Thanks, I was able to install the plugin now. 
@matmair I was just confused from reading the docs, not much details about each fields. 

After installing, do I need to restart the server? No error but the plugin doesn't show up in the list either.

**Comment by tristanle22** [comment]
What exactly does this toggle button mean:

Confirm plugin installation
This will install this plugin now into the current instance. The instance will go into maintenance.

**Comment by tristanle22** [comment]
@SergeoLacruz May I ask what version of Inventree are you using, and whether you're running a production server with Docker? I can install the plugin no problem in my devcontainer, but still doesn't work with 0.17.11 in docker.

**Comment by SergeoLacruz** [comment]
I tried it on 0.17.0 baremetal development server.

**Comment by tristanle22** [comment]
And may I ask what's your python version?

**Comment by SergeoLacruz** [comment]
3.10.12

**Comment by SchrodingersGat** [comment]
@tristanle22 given your error messages there may be something incorrect with the plugin source.

Would you mind sharing a link to the plugin source (if it is publicly available)?

**Comment by SergeoLacruz** [comment]
I triedt this one

https://github.com/AlexLe68/ExtraExchangeRate

Took the install from pypi

**Comment by tristanle22** [comment]
The "Project-URL" error is caused by Python version. I developed with Python 3.11, but my server was running with Python 3.9. So some metadata dynamic loading didn't work, hence the error. The issue was resolved after upgrading to Python 3.11.

**Comment by matmair** [comment]
So we can close this?

**Comment by tristanle22** [comment]
Sounds good.

**Comment by MrARM** [comment]
This is still an issue when attempting to install plugins from a custom pypi server.

For now, I've managed to bypass it by tricking the installer into thinking my installation of a wheel file is a svn repository https://github.com/inventree/InvenTree/blob/b048ca3a043633e932cd946dc00df7102de7e224/src/backend/InvenTree/plugin/installer.py#L255

However, this method would need to be performed every time I update my plugin, as I am locking a version by specifying a wheel URL.
